FIXUP: BACKPORT: FROMLIST: virtio_video: Add the Virtio Video V4L2 driver
0-day reports:

drivers/media/virtio/virtio_video_device.c:1188:6: error:
	no previous prototype for 'virtio_video_device_destroy'
drivers/media/virtio/virtio_video_helpers.c:188:10: error:
	no previous prototype for 'virtio_video_get_format_from_virtio_profile'

Somewhat guessing here, virtio_video_device_destroy() is only called
locally and thus marked static.
virtio_video_get_format_from_virtio_profile() is not called at all and
presumably intended to be used as helper function. Removed this function,
as the conversion from a profile to a format doesn't make much sense.
If we need a V4L2 format, we should virtio_video_format_to_v4l2 instead.

BUG=b:120456557, b:151703605
TEST=compile with VIRTIO_VIDEO enabled

Change-Id: I02d577f8e9b1a65cbbe9877391f8f755a474fc78
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Keiichi Watanabe <keiichiw@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2226628
[5.4-arcvm: picked from 5.4 for initial merge]